const config = {
    "default_font": "",
    "default_font_size": "16",
    "default_text_color": "white",
    "default_background_color": "",
    "text_box_img": "text-window.png",
    "name_box_img": "",
    "next_button_img": "",
    "next_button_img_hover": "",
    "option_button_color": "",
    "option_button_color_hover": "",
    "text_speed": "",
    "text_sound": ""
}

const data = {
    "1": {
        "node_id": "1",
        "display_mode": "text",
        "sound": "sound/sound.wav",
        "setting_mode": "",
        "setting_back": "img/hht_rough_forest01.19.jpg",
        "setting_back_animation": "",
        "setting_back_opacity": "",
        "setting_mid": "",
        "setting_mid_animation": "",
        "setting_mid_opacity": "",
        "setting_front": "",
        "setting_front_animation": "",
        "setting_front_opacity": "",
        "text_color": "",
        "text_font": "",
        "name": "Jordan",
        "name_position": "left",
        "line_1_text": "Hey! Just wanted to say hi and touch",
        "line_2_text": "base with you, This week has been ",
        "line_3_text": "crazy. What have you been up to?",
        "option_description": "",
        "option_description_color": "",
        "option_1_text": "tset",
        "option_2_text": "this is a test ",
        "option_3_text": "another test",
        "option_1_output": "",
        "option_2_output": "",
        "option_3_output": "",
        "img_left": "img/char.png",
        "img_center": "",
        "img_right": "",
        "img_left_animation": "",
        "img_center_animation": "",
        "img_right_animation": "",
        "scene_length": "",
        "output": "2"
    },
    "2": {
        "node_id": "2",
        "display_mode": "scene",
        "sound": "sound/sound.wav",
        "setting_mode": "",
        "setting_back": "img/hht_rough_forest01.19.jpg",
        "setting_back_animation": "",
        "setting_back_opacity": "0.8",
        "setting_mid": "",
        "setting_mid_animation": "",
        "setting_mid_opacity": "",
        "setting_front": "",
        "setting_front_animation": "",
        "setting_front_opacity": "",
        "text_color": "",
        "text_font": "",
        "name": "",
        "name_position": "",
        "line_1_text": "",
        "line_2_text": "",
        "line_3_text": "",
        "option_description": "",
        "option_description_color": "",
        "option_1_text": "",
        "option_2_text": "",
        "option_3_text": "",
        "option_1_output": "",
        "option_2_output": "",
        "option_3_output": "",
        "img_left": "",
        "img_center": "img/char.png",
        "img_right": "",
        "img_left_animation": "",
        "img_center_animation": "",
        "img_right_animation": "",
        "scene_length": "5000",
        "output": "3"
    },
    "3": {
        "node_id": "3",
        "display_mode": "option",
        "sound": "",
        "setting_mode": "",
        "setting_back": "img/hht_rough_forest01.19.jpg",
        "setting_back_animation": "",
        "setting_back_opacity": "",
        "setting_mid": "",
        "setting_mid_animation": "",
        "setting_mid_opacity": "",
        "setting_front": "",
        "setting_front_animation": "",
        "setting_front_opacity": "",
        "text_color": "",
        "text_font": "",
        "name": "",
        "name_position": "",
        "line_1_text": "",
        "line_2_text": "",
        "line_3_text": "",
        "option_description": "What would you like to do?",
        "option_description_color": "",
        "option_1_text": "Go to work.",
        "option_2_text": "Stay home.",
        "option_3_text": "Do literally nothing.",
        "option_1_output": "1",
        "option_2_output": "1",
        "option_3_output": "1",
        "img_left": "",
        "img_center": "",
        "img_right": "img/char.png",
        "img_left_animation": "",
        "img_center_animation": "",
        "img_right_animation": "",
        "scene_length": "",
        "output": ""
    }
}